version: '3'
services:
  cassandra:
    image: cassandra:latest
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  annotator:
    image: annotator_supreme:no_nginx
    hostname: annotator.dev.intranet
    volumes:
    - ./:/code
    depends_on:
    - cassandra
    environment:
    - CLUSTER_IP=cassandra
    ports:
    - "4242:4242"
    
  nginx:
    image: custom-nginx:latest
    depends_on:
    - annotator
    ports:
    - "4280:80"
